targets:
  $default:
    builders:
      # Configure Riverpod generator
      riverpod_generator:
        enabled: true
        
      # Configure other generators
      openapi_generator:
        options:
          input: api/openapi.yaml
          output: lib/api
          generator_name: dart2
          global_options:
            verbose: true
          additional_properties:
            pubName: flutter_memos_api
            pubVersion: 1.0.0
            useEnumExtension: true
            dateLibrary: time
        generate_for:
          - lib/api/**
        
      # Disable retrofit generator for Riverpod files
      retrofit_generator:
        generate_for:
          exclude:
            - lib/providers/**
