services:
  # --- Existing Memos Service ---
  memos:
    image: neosmemo/memos:0.24.0 # Use a specific version
    container_name: memos-server
    environment:
      MEMOS_MODE: 'prod'
      MEMOS_PORT: '5230'
      TZ: 'UTC'
    volumes:
      - ./memos-data:/var/opt/memos
    ports:
      - '5230:5230' # Memos UI/API port
    restart: unless-stopped

  # --- New MCP Proxy Service (Using Go) ---
  mcp_proxy:
    build:
      # Set context to the project root directory
      context: .
      # Specify the Dockerfile path relative to the new context
      dockerfile: ./api/mcp_tcp_proxy_go/Dockerfile
    container_name: mcp-proxy-server-go # Renamed container for clarity
    environment:
      # Pass secrets needed by the stdio servers here.
      # The Go proxy reads os.Environ() and passes it down.
      # Make sure these are set in your host environment or a .env file.
      TODOIST_API_TOKEN: ${TODOIST_API_TOKEN}
      # Add other secrets like OPENAI_API_KEY if needed by other MCP servers
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      # Map host port 8999 to container port 8999 (defined by PROXY_PORT in Dockerfile)
      - '8999:8999'
    restart: unless-stopped
    # depends_on: # Add if the proxy relies on Memos, unlikely here
    #  - memos

volumes:
  memos-data: # Define the named volume used by Memos
# Ensure the volumes section is correctly placed at the end of the file