services:
  # --- Existing Memos Service ---
  memos:
    image: neosmemo/memos:0.24.0 # Use a specific version
    container_name: memos-server
    environment:
      MEMOS_MODE: 'prod'
      MEMOS_PORT: '5230'
      TZ: 'UTC'
    volumes:
      - ./memos-data:/var/opt/memos
    ports:
      - '5230:5230' # Memos UI/API port
    restart: unless-stopped

  # --- New MCP SSE Time Server Service ---
  mcp_sse_time_server:
    build:
      # Set context to the directory containing the Dockerfile
      context: ./api/mcp_sse_time_server_dart
      # Specify the Dockerfile name within that context
      dockerfile: Dockerfile
    container_name: mcp-sse-time-server
    # No environment variables needed for this simple server
    # environment:
    #   PORT: 8999 # Optional: Can override the default port in the Dockerfile
    ports:
      # Map host port 8999 to container port 8999 (exposed in Dockerfile)
      - '8999:8999'
    restart: unless-stopped

volumes:
  memos-data: # Define the named volume used by Memos
# Ensure the volumes section is correctly placed at the end of the file
