name: flutter_memos
description: "A Flutter version of the memo app with assistant chat functionality."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.3.0
  provider: ^6.0.5
  flutter_riverpod: ^2.4.9
  url_launcher: ^6.1.12
  retrofit: ^4.0.3
  built_value: ^8.6.1
  openapi_generator_annotations: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  openapi_generator: ^6.1.0
  openapi_generator_cli: ^6.1.0
  retrofit_generator: ^9.1.9
  built_value_generator: ^8.6.1
  mockito: ^5.4.4
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.7
  # NOTE: these usually mess with when you try to migrate to generated code
  # NOTE: Keep the following commented out until you migrate to generated code:
  # riverpod_generator: ^2.1.5
  # riverpod_annotation: ^2.1.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
