name: flutter_memos
description: "A Flutter version of the memo app with assistant chat functionality."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2 # Keep this constraint

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Ensure localizations is present
    sdk: flutter

  # Cupertino specific icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5 # Keep if using annotations

  # Persistence
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2 # Keep specific version

  # Networking & API
  http: ^1.2.1
  protobuf: ^3.1.0 # Keep if needed by dependencies
  grpc: ^3.2.4 # Keep if needed by dependencies
  retrofit: ^4.0.3 # Keep if using retrofit
  built_value: ^8.6.1 # Keep if using built_value

  # Deep Linking / App Links
  app_links: ^6.0.1 # Keep specific version

  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  flutter_highlight: ^0.7.0 # Keep if using syntax highlighting
  highlight: ^0.7.0 # Core library for flutter_highlight
  path_provider: ^2.1.3
  uuid: ^4.5.1 # Keep specific version from plan
  collection: ^1.19.1 # Keep specific version from plan
  flutter_keyboard_visibility: ^6.0.0
  flutter_markdown: ^0.7.7 # Keep specific version from plan
  google_generative_ai: ^0.4.6 # Keep specific version from plan
  openai_dart: ^0.4.5 # Keep override version
  synchronized: ^3.1.0+1 # Keep override version

  # CloudKit Integration
  flutter_cloud_kit: ^0.0.3 # Keep override version

  # MCP Integration
  # Ensure any git or hosted version is commented out
  # mcp_dart: ^0.3.x
  # mcp_dart:
  #   git: ...
  # Use the local path override
  mcp_dart:
    path: ../mcp_dart # Verify this path is correct relative to pubspec.yaml

  # Other existing dependencies
  flutter_slidable: ^4.0.0
  sqflite: ^2.3.0
  provider: ^6.0.5 # Keep if still used alongside Riverpod
  file_picker: ^10.0.0
  markdown: # Keep git override
    git:
      url: https://github.com/dart-lang/tools.git
      path: pkgs/markdown
      ref: main

  # Crash Reporting
  sentry_flutter: ^8.14.1

dependency_overrides:
  markdown: # Keep git override
    git:
      url: https://github.com/dart-lang/tools.git
      path: pkgs/markdown
      ref: main
  flutter_markdown: # Keep git override
    git:
      url: https://github.com/flutter/packages
      path: packages/flutter_markdown
      ref: main
  uuid: ^4.5.1 # Keep override
  flutter_cloud_kit: ^0.0.3 # Keep override
  openai_dart: ^0.4.5 # Keep override
  synchronized: ^3.1.0+1 # Keep override
  # Ensure any git or hosted version is commented out
  # mcp_dart:
  #   git: ...
  # Use the local path override
  mcp_dart: ^0.3.6 # Keep specific version from plan
  # mcp_dart:
    # path: ../mcp_dart # Verify this path is correct relative to pubspec.yaml

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Use a specific version or range if needed
  test: ^1.24.9

  build_runner: ^2.4.6
  retrofit_generator: ^9.1.9 # Keep if using retrofit
  built_value_generator: ^8.6.1 # Keep if using built_value
  mockito: ^5.4.4
  custom_lint: ^0.7.0 # Keep if using custom lints
  riverpod_lint: ^2.6.3 # Keep if using riverpod_lint
  meta: ^1.12.0 # Add meta package

  # NOTE: Keep the following commented out until you migrate to generated code:
  # riverpod_generator: ^2.1.5
  # riverpod_annotation: ^2.1.5

flutter:
  uses-material-design: true
