// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_memos/test/services/chat_ai_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_memos/models/mcp_server_config.dart' as _i7;
import 'package:flutter_memos/services/chat_ai.dart' as _i2;
import 'package:flutter_memos/services/mcp_client_service.dart' as _i4;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:google_generative_ai/google_generative_ai.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatAiResponse_0 extends _i1.SmartFake
    implements _i2.ChatAiResponse {
  _FakeChatAiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRef_1<State extends Object?> extends _i1.SmartFake
    implements _i3.Ref<State> {
  _FakeRef_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMcpClientState_2 extends _i1.SmartFake
    implements _i4.McpClientState {
  _FakeMcpClientState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMcpProcessResult_3 extends _i1.SmartFake
    implements _i4.McpProcessResult {
  _FakeMcpProcessResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatAiBackend].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatAiBackend extends _i1.Mock implements _i2.ChatAiBackend {
  @override
  _i5.Future<_i2.ChatAiResponse> send(
    List<_i6.Content>? history,
    String? userMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [
            history,
            userMessage,
          ],
        ),
        returnValue: _i5.Future<_i2.ChatAiResponse>.value(_FakeChatAiResponse_0(
          this,
          Invocation.method(
            #send,
            [
              history,
              userMessage,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ChatAiResponse>.value(_FakeChatAiResponse_0(
          this,
          Invocation.method(
            #send,
            [
              history,
              userMessage,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ChatAiResponse>);
}

/// A class which mocks [McpClientNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMcpClientNotifier extends _i1.Mock implements _i4.McpClientNotifier {
  @override
  _i3.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_1<Object?>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeRef_1<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i3.Ref<Object?>);

  @override
  Map<String, String> get toolToServerIdMap => (super.noSuchMethod(
        Invocation.getter(#toolToServerIdMap),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  set toolToServerIdMap(Map<String, String>? _toolToServerIdMap) =>
      super.noSuchMethod(
        Invocation.setter(
          #toolToServerIdMap,
          _toolToServerIdMap,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set serverListSubscription(
          _i3.ProviderSubscription<List<_i7.McpServerConfig>>?
              _serverListSubscription) =>
      super.noSuchMethod(
        Invocation.setter(
          #serverListSubscription,
          _serverListSubscription,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasActiveConnections => (super.noSuchMethod(
        Invocation.getter(#hasActiveConnections),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Stream<_i4.McpClientState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i4.McpClientState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i4.McpClientState>.empty(),
      ) as _i5.Stream<_i4.McpClientState>);

  @override
  _i4.McpClientState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMcpClientState_2(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeMcpClientState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.McpClientState);

  @override
  set state(_i4.McpClientState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.McpClientState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeMcpClientState_2(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeMcpClientState_2(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i4.McpClientState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> connectServer(_i7.McpServerConfig? serverConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectServer,
          [serverConfig],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectServer(String? serverId) => (super.noSuchMethod(
        Invocation.method(
          #disconnectServer,
          [serverId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void syncConnections() => super.noSuchMethod(
        Invocation.method(
          #syncConnections,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateServerState(
    String? serverId,
    _i4.McpConnectionStatus? status, {
    String? errorMsg,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateServerState,
          [
            serverId,
            status,
          ],
          {#errorMsg: errorMsg},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleClientError(
    String? serverId,
    String? errorMsg,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleClientError,
          [
            serverId,
            errorMsg,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleClientClose(String? serverId) => super.noSuchMethod(
        Invocation.method(
          #handleClientClose,
          [serverId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rebuildToolMap() => super.noSuchMethod(
        Invocation.method(
          #rebuildToolMap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.McpProcessResult> processQuery(
    String? query,
    List<_i6.Content>? history,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processQuery,
          [
            query,
            history,
          ],
        ),
        returnValue:
            _i5.Future<_i4.McpProcessResult>.value(_FakeMcpProcessResult_3(
          this,
          Invocation.method(
            #processQuery,
            [
              query,
              history,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.McpProcessResult>.value(_FakeMcpProcessResult_3(
          this,
          Invocation.method(
            #processQuery,
            [
              query,
              history,
            ],
          ),
        )),
      ) as _i5.Future<_i4.McpProcessResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i4.McpClientState? old,
    _i4.McpClientState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.RemoveListener addListener(
    _i8.Listener<_i4.McpClientState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i3.RemoveListener);
}
