name: mcp_tcp_proxy
description: A TCP proxy gateway for stdio-based MCP servers (Dart implementation).
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0 # For command-line argument parsing (e.g., port)
  # No direct mcp_dart dependency needed here, as it interacts via Process stdio

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0