name: mcp_sse_time_server_dart
description: A simple MCP server demonstrating SSE transport using mcp_dart's SseServerManager.
version: 0.1.0
# repository: https://github.com/your_repo/mcp_sse_time_server_dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mcp_dart: ^0.3.6 # Ensure this matches the version used by flutter_memos
  shelf: ^1.4.0
  shelf_router: ^1.1.0 # Keep shelf_router if needed for other potential routes, though SseServerManager handles its own.

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
