name: mcp_sse_todoist_server_dart
description: MCP server providing Todoist tools via SSE, designed for Docker.
version: 0.1.0
# repository: <optional_repo_link>

environment:
  sdk: '>=3.0.0 <4.0.0' # Match the main project or adjust as needed

dependencies:
  # MCP library
  mcp_dart: ^0.3.6 # Use the same version as the main project or latest compatible

  # ADD: HTTP client for API calls
  http: ^1.2.1

  # ADD: Path dependency to the *local* generated Todoist API client
  # This directory should be copied into api/mcp_sse_todoist_server_dart/
  todoist_api:
    path: ../../lib/todoist_api/ # Corrected relative path

  # Add other direct dependencies if needed (e.g., collection if used directly)
  collection: ^1.18.0 # For safe casting, etc.

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0