// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_memos/test/features/memos/providers/move_memo_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i10;

import 'package:flutter_memos/api/lib/api.dart' as _i4;
import 'package:flutter_memos/models/comment.dart' as _i5;
import 'package:flutter_memos/models/memo.dart' as _i3;
import 'package:flutter_memos/models/memo_relation.dart' as _i11;
import 'package:flutter_memos/models/server_config.dart' as _i9;
import 'package:flutter_memos/providers/memo_providers.dart' as _i6;
import 'package:flutter_memos/services/api_service.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:state_notifier/state_notifier.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedMemoResponse_0 extends _i1.SmartFake
    implements _i2.PaginatedMemoResponse {
  _FakePaginatedMemoResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemo_1 extends _i1.SmartFake implements _i3.Memo {
  _FakeMemo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeV1Resource_2 extends _i1.SmartFake implements _i4.V1Resource {
  _FakeV1Resource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComment_3 extends _i1.SmartFake implements _i5.Comment {
  _FakeComment_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemosState_4 extends _i1.SmartFake implements _i6.MemosState {
  _FakeMemosState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  @override
  String get apiBaseUrl => (super.noSuchMethod(
        Invocation.getter(#apiBaseUrl),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#apiBaseUrl),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#apiBaseUrl),
        ),
      ) as String);

  @override
  void configureService({
    required String? baseUrl,
    required String? authToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #configureService,
          [],
          {
            #baseUrl: baseUrl,
            #authToken: authToken,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i2.PaginatedMemoResponse> listMemos({
    String? parent = 'users/1',
    String? filter,
    String? state,
    String? sort = 'updateTime',
    String? direction = 'DESC',
    int? pageSize,
    String? pageToken,
    List<String>? tags,
    dynamic visibility,
    String? contentSearch,
    DateTime? createdAfter,
    DateTime? createdBefore,
    DateTime? updatedAfter,
    DateTime? updatedBefore,
    String? timeExpression,
    bool? useUpdateTimeForExpression = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMemos,
          [],
          {
            #parent: parent,
            #filter: filter,
            #state: state,
            #sort: sort,
            #direction: direction,
            #pageSize: pageSize,
            #pageToken: pageToken,
            #tags: tags,
            #visibility: visibility,
            #contentSearch: contentSearch,
            #createdAfter: createdAfter,
            #createdBefore: createdBefore,
            #updatedAfter: updatedAfter,
            #updatedBefore: updatedBefore,
            #timeExpression: timeExpression,
            #useUpdateTimeForExpression: useUpdateTimeForExpression,
          },
        ),
        returnValue: _i8.Future<_i2.PaginatedMemoResponse>.value(
            _FakePaginatedMemoResponse_0(
          this,
          Invocation.method(
            #listMemos,
            [],
            {
              #parent: parent,
              #filter: filter,
              #state: state,
              #sort: sort,
              #direction: direction,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #tags: tags,
              #visibility: visibility,
              #contentSearch: contentSearch,
              #createdAfter: createdAfter,
              #createdBefore: createdBefore,
              #updatedAfter: updatedAfter,
              #updatedBefore: updatedBefore,
              #timeExpression: timeExpression,
              #useUpdateTimeForExpression: useUpdateTimeForExpression,
            },
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i2.PaginatedMemoResponse>.value(
            _FakePaginatedMemoResponse_0(
          this,
          Invocation.method(
            #listMemos,
            [],
            {
              #parent: parent,
              #filter: filter,
              #state: state,
              #sort: sort,
              #direction: direction,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #tags: tags,
              #visibility: visibility,
              #contentSearch: contentSearch,
              #createdAfter: createdAfter,
              #createdBefore: createdBefore,
              #updatedAfter: updatedAfter,
              #updatedBefore: updatedBefore,
              #timeExpression: timeExpression,
              #useUpdateTimeForExpression: useUpdateTimeForExpression,
            },
          ),
        )),
      ) as _i8.Future<_i2.PaginatedMemoResponse>);

  @override
  _i8.Future<_i3.Memo> getMemo(
    String? id, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemo,
          [id],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #getMemo,
            [id],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #getMemo,
            [id],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
      ) as _i8.Future<_i3.Memo>);

  @override
  _i8.Future<_i3.Memo> createMemo(
    _i3.Memo? memo, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMemo,
          [memo],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #createMemo,
            [memo],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #createMemo,
            [memo],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
      ) as _i8.Future<_i3.Memo>);

  @override
  _i8.Future<_i3.Memo> updateMemo(
    String? id,
    _i3.Memo? memo, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemo,
          [
            id,
            memo,
          ],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #updateMemo,
            [
              id,
              memo,
            ],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #updateMemo,
            [
              id,
              memo,
            ],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
      ) as _i8.Future<_i3.Memo>);

  @override
  _i8.Future<void> deleteMemo(
    String? id, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMemo,
          [id],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.V1Resource> uploadResource(
    _i10.Uint8List? fileBytes,
    String? filename,
    String? contentType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadResource,
          [
            fileBytes,
            filename,
            contentType,
          ],
        ),
        returnValue: _i8.Future<_i4.V1Resource>.value(_FakeV1Resource_2(
          this,
          Invocation.method(
            #uploadResource,
            [
              fileBytes,
              filename,
              contentType,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.V1Resource>.value(_FakeV1Resource_2(
          this,
          Invocation.method(
            #uploadResource,
            [
              fileBytes,
              filename,
              contentType,
            ],
          ),
        )),
      ) as _i8.Future<_i4.V1Resource>);

  @override
  _i8.Future<List<_i5.Comment>> listMemoComments(
    String? memoId, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMemoComments,
          [memoId],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<List<_i5.Comment>>.value(<_i5.Comment>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i5.Comment>>.value(<_i5.Comment>[]),
      ) as _i8.Future<List<_i5.Comment>>);

  @override
  _i8.Future<_i5.Comment> createMemoComment(
    String? memoId,
    _i5.Comment? comment, {
    List<_i4.V1Resource>? resources,
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMemoComment,
          [
            memoId,
            comment,
          ],
          {
            #resources: resources,
            #targetServerOverride: targetServerOverride,
          },
        ),
        returnValue: _i8.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #createMemoComment,
            [
              memoId,
              comment,
            ],
            {
              #resources: resources,
              #targetServerOverride: targetServerOverride,
            },
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #createMemoComment,
            [
              memoId,
              comment,
            ],
            {
              #resources: resources,
              #targetServerOverride: targetServerOverride,
            },
          ),
        )),
      ) as _i8.Future<_i5.Comment>);

  @override
  _i8.Future<_i5.Comment> getMemoComment(
    String? commentId, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemoComment,
          [commentId],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #getMemoComment,
            [commentId],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #getMemoComment,
            [commentId],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
      ) as _i8.Future<_i5.Comment>);

  @override
  _i8.Future<_i5.Comment> updateMemoComment(
    String? commentId,
    _i5.Comment? comment, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemoComment,
          [
            commentId,
            comment,
          ],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #updateMemoComment,
            [
              commentId,
              comment,
            ],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #updateMemoComment,
            [
              commentId,
              comment,
            ],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
      ) as _i8.Future<_i5.Comment>);

  @override
  _i8.Future<void> deleteMemoComment(
    String? memoId,
    String? commentId, {
    _i9.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMemoComment,
          [
            memoId,
            commentId,
          ],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setMemoRelations(
    String? memoId,
    List<_i11.MemoRelation>? relations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMemoRelations,
          [
            memoId,
            relations,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i11.MemoRelation>> listMemoRelations(String? memoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMemoRelations,
          [memoId],
        ),
        returnValue:
            _i8.Future<List<_i11.MemoRelation>>.value(<_i11.MemoRelation>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i11.MemoRelation>>.value(<_i11.MemoRelation>[]),
      ) as _i8.Future<List<_i11.MemoRelation>>);

  @override
  String parseRelationType(dynamic type) => (super.noSuchMethod(
        Invocation.method(
          #parseRelationType,
          [type],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #parseRelationType,
            [type],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #parseRelationType,
            [type],
          ),
        ),
      ) as String);
}

/// A class which mocks [MemosNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemosNotifier extends _i1.Mock implements _i6.MemosNotifier {
  @override
  set onError(_i12.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Stream<_i6.MemosState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i6.MemosState>.empty(),
        returnValueForMissingStub: _i8.Stream<_i6.MemosState>.empty(),
      ) as _i8.Stream<_i6.MemosState>);

  @override
  _i6.MemosState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMemosState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeMemosState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.MemosState);

  @override
  set state(_i6.MemosState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.MemosState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeMemosState_4(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeMemosState_4(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i6.MemosState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Future<void> fetchInitialPage() => (super.noSuchMethod(
        Invocation.method(
          #fetchInitialPage,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> fetchMoreMemos() => (super.noSuchMethod(
        Invocation.method(
          #fetchMoreMemos,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void updateMemoOptimistically(_i3.Memo? updatedMemo) => super.noSuchMethod(
        Invocation.method(
          #updateMemoOptimistically,
          [updatedMemo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeMemoOptimistically(String? memoId) => super.noSuchMethod(
        Invocation.method(
          #removeMemoOptimistically,
          [memoId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void archiveMemoOptimistically(String? memoId) => super.noSuchMethod(
        Invocation.method(
          #archiveMemoOptimistically,
          [memoId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePinOptimistically(String? memoId) => super.noSuchMethod(
        Invocation.method(
          #togglePinOptimistically,
          [memoId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void bumpMemoOptimistically(String? memoId) => super.noSuchMethod(
        Invocation.method(
          #bumpMemoOptimistically,
          [memoId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i6.MemosState? old,
    _i6.MemosState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i12.RemoveListener addListener(
    _i13.Listener<_i6.MemosState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i12.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
