// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_memos/test/features/comments/providers/comment_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i9;

import 'package:flutter_memos/api/lib/api.dart' as _i4;
import 'package:flutter_memos/models/comment.dart' as _i5;
import 'package:flutter_memos/models/memo.dart' as _i3;
import 'package:flutter_memos/models/memo_relation.dart' as _i10;
import 'package:flutter_memos/models/server_config.dart' as _i8;
import 'package:flutter_memos/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedMemoResponse_0 extends _i1.SmartFake
    implements _i2.PaginatedMemoResponse {
  _FakePaginatedMemoResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemo_1 extends _i1.SmartFake implements _i3.Memo {
  _FakeMemo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeV1Resource_2 extends _i1.SmartFake implements _i4.V1Resource {
  _FakeV1Resource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComment_3 extends _i1.SmartFake implements _i5.Comment {
  _FakeComment_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  @override
  String get apiBaseUrl => (super.noSuchMethod(
        Invocation.getter(#apiBaseUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#apiBaseUrl),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#apiBaseUrl),
        ),
      ) as String);

  @override
  void configureService({
    required String? baseUrl,
    required String? authToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #configureService,
          [],
          {
            #baseUrl: baseUrl,
            #authToken: authToken,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.PaginatedMemoResponse> listMemos({
    String? parent = 'users/1',
    String? filter,
    String? state,
    String? sort = 'updateTime',
    String? direction = 'DESC',
    int? pageSize,
    String? pageToken,
    List<String>? tags,
    dynamic visibility,
    String? contentSearch,
    DateTime? createdAfter,
    DateTime? createdBefore,
    DateTime? updatedAfter,
    DateTime? updatedBefore,
    String? timeExpression,
    bool? useUpdateTimeForExpression = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMemos,
          [],
          {
            #parent: parent,
            #filter: filter,
            #state: state,
            #sort: sort,
            #direction: direction,
            #pageSize: pageSize,
            #pageToken: pageToken,
            #tags: tags,
            #visibility: visibility,
            #contentSearch: contentSearch,
            #createdAfter: createdAfter,
            #createdBefore: createdBefore,
            #updatedAfter: updatedAfter,
            #updatedBefore: updatedBefore,
            #timeExpression: timeExpression,
            #useUpdateTimeForExpression: useUpdateTimeForExpression,
          },
        ),
        returnValue: _i7.Future<_i2.PaginatedMemoResponse>.value(
            _FakePaginatedMemoResponse_0(
          this,
          Invocation.method(
            #listMemos,
            [],
            {
              #parent: parent,
              #filter: filter,
              #state: state,
              #sort: sort,
              #direction: direction,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #tags: tags,
              #visibility: visibility,
              #contentSearch: contentSearch,
              #createdAfter: createdAfter,
              #createdBefore: createdBefore,
              #updatedAfter: updatedAfter,
              #updatedBefore: updatedBefore,
              #timeExpression: timeExpression,
              #useUpdateTimeForExpression: useUpdateTimeForExpression,
            },
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i2.PaginatedMemoResponse>.value(
            _FakePaginatedMemoResponse_0(
          this,
          Invocation.method(
            #listMemos,
            [],
            {
              #parent: parent,
              #filter: filter,
              #state: state,
              #sort: sort,
              #direction: direction,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #tags: tags,
              #visibility: visibility,
              #contentSearch: contentSearch,
              #createdAfter: createdAfter,
              #createdBefore: createdBefore,
              #updatedAfter: updatedAfter,
              #updatedBefore: updatedBefore,
              #timeExpression: timeExpression,
              #useUpdateTimeForExpression: useUpdateTimeForExpression,
            },
          ),
        )),
      ) as _i7.Future<_i2.PaginatedMemoResponse>);

  @override
  _i7.Future<_i3.Memo> getMemo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMemo,
          [id],
        ),
        returnValue: _i7.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #getMemo,
            [id],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #getMemo,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.Memo>);

  @override
  _i7.Future<_i3.Memo> createMemo(
    _i3.Memo? memo, {
    _i8.ServerConfig? targetServerOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMemo,
          [memo],
          {#targetServerOverride: targetServerOverride},
        ),
        returnValue: _i7.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #createMemo,
            [memo],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #createMemo,
            [memo],
            {#targetServerOverride: targetServerOverride},
          ),
        )),
      ) as _i7.Future<_i3.Memo>);

  @override
  _i7.Future<_i3.Memo> updateMemo(
    String? id,
    _i3.Memo? memo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemo,
          [
            id,
            memo,
          ],
        ),
        returnValue: _i7.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #updateMemo,
            [
              id,
              memo,
            ],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Memo>.value(_FakeMemo_1(
          this,
          Invocation.method(
            #updateMemo,
            [
              id,
              memo,
            ],
          ),
        )),
      ) as _i7.Future<_i3.Memo>);

  @override
  _i7.Future<void> deleteMemo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMemo,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.V1Resource> uploadResource(
    _i9.Uint8List? fileBytes,
    String? filename,
    String? contentType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadResource,
          [
            fileBytes,
            filename,
            contentType,
          ],
        ),
        returnValue: _i7.Future<_i4.V1Resource>.value(_FakeV1Resource_2(
          this,
          Invocation.method(
            #uploadResource,
            [
              fileBytes,
              filename,
              contentType,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i4.V1Resource>.value(_FakeV1Resource_2(
          this,
          Invocation.method(
            #uploadResource,
            [
              fileBytes,
              filename,
              contentType,
            ],
          ),
        )),
      ) as _i7.Future<_i4.V1Resource>);

  @override
  _i7.Future<List<_i5.Comment>> listMemoComments(String? memoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMemoComments,
          [memoId],
        ),
        returnValue: _i7.Future<List<_i5.Comment>>.value(<_i5.Comment>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.Comment>>.value(<_i5.Comment>[]),
      ) as _i7.Future<List<_i5.Comment>>);

  @override
  _i7.Future<_i5.Comment> createMemoComment(
    String? memoId,
    _i5.Comment? comment, {
    List<_i4.V1Resource>? resources,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMemoComment,
          [
            memoId,
            comment,
          ],
          {#resources: resources},
        ),
        returnValue: _i7.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #createMemoComment,
            [
              memoId,
              comment,
            ],
            {#resources: resources},
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #createMemoComment,
            [
              memoId,
              comment,
            ],
            {#resources: resources},
          ),
        )),
      ) as _i7.Future<_i5.Comment>);

  @override
  _i7.Future<_i5.Comment> getMemoComment(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemoComment,
          [commentId],
        ),
        returnValue: _i7.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #getMemoComment,
            [commentId],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #getMemoComment,
            [commentId],
          ),
        )),
      ) as _i7.Future<_i5.Comment>);

  @override
  _i7.Future<_i5.Comment> updateMemoComment(
    String? commentId,
    _i5.Comment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemoComment,
          [
            commentId,
            comment,
          ],
        ),
        returnValue: _i7.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #updateMemoComment,
            [
              commentId,
              comment,
            ],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i5.Comment>.value(_FakeComment_3(
          this,
          Invocation.method(
            #updateMemoComment,
            [
              commentId,
              comment,
            ],
          ),
        )),
      ) as _i7.Future<_i5.Comment>);

  @override
  _i7.Future<void> deleteMemoComment(
    String? memoId,
    String? commentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMemoComment,
          [
            memoId,
            commentId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setMemoRelations(
    String? memoId,
    List<_i10.MemoRelation>? relations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMemoRelations,
          [
            memoId,
            relations,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.MemoRelation>> listMemoRelations(String? memoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMemoRelations,
          [memoId],
        ),
        returnValue:
            _i7.Future<List<_i10.MemoRelation>>.value(<_i10.MemoRelation>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i10.MemoRelation>>.value(<_i10.MemoRelation>[]),
      ) as _i7.Future<List<_i10.MemoRelation>>);

  @override
  String parseRelationType(dynamic type) => (super.noSuchMethod(
        Invocation.method(
          #parseRelationType,
          [type],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #parseRelationType,
            [type],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #parseRelationType,
            [type],
          ),
        ),
      ) as String);
}
